<div class="relative p-8 w-full h-full bg-white z-10 rounded-xl">
    <div class="flex flex-row gap-6">
        <div class="flex items-center px-10 py-6 rounded-xl bg-gray-200">
            <h1 class="text-4xl font-bold whitespace-nowrap">Modal Title</h1>
        </div>
        <div class="flex item-center w-full px-8 py-6 rounded-xl bg-gray-100">
        </div>
    </div>
    <div class="flex flex-col gap-6 w-full px-10 my-8 py-12 rounded-xl bg-gray-200">
        <div class="flex flex-row w-full px-10 py-6 rounded-xl bg-gray-100">
            <span class="font-bold">Task Title:</span>
            <span></span>
        </div>
        <div class="flex flex-row w-full px-10 py-6 rounded-xl bg-gray-100">
            <span class="font-bold">Task Description:</span>
        </div>
        <div class="flex flex-row w-full px-10 py-6 rounded-xl bg-gray-100">
            <span class="font-bold">Task Status:</span>
        </div>
        <div class="flex flex-row w-full px-10 py-6 rounded-xl bg-gray-100">
            <span class="font-bold">Task Due Date:</span>
        </div>
        <div class="flex flex-row w-full px-10 py-6 rounded-xl bg-gray-100">
            <span class="font-bold">Modified Date:</span>
        </div>
        <div class="flex flex-row w-full px-10 py-6 rounded-xl bg-gray-100">
            <span class="font-bold">Created Date:</span>
        </div>
    </div>
</div>